### ISSUE TITLE
Google Chrome net::ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by andi69** [RexDude/seo42#162]
In der .htaccess führt der deflate:
  AddOutputFilterByType DEFLATE text/html

zum Error: 
  net::ERR_SPDY_PROTOCOL_ERROR

Chrome Version 40.0.2214.89 - Android 4.4.4
http://dev.chromium.org/spdy/spdy-whitepaper

Meine Lösung: deflate text/html in der .htaccess deaktivieren

**Comment by RexDude** [comment]
Die Html Seite sollten aber komprimiert ausgeliefert werden. Abschalten ist daher eigentlich keine Option.
