### ISSUE TITLE
Bei Installation überprüfen ob andere Rewrite Addons installiert sind

### ISSUE THREAD

**Issue by Sysix-Coding** [RexDude/seo42#163]
Hallöchen,

ist bestimmt eine nette Sache, da im Forum schon desöfteren solche Fehler entstehen.

**Comment by RexDude** [comment]
Passiert schon, ne?

**Comment by Sysix-Coding** [comment]
Jop^^ aber wieso kommen im Forum noch solche fehler auf :D?

**Comment by RexDude** [comment]
wo denn? schick mal pm.
