### ISSUE TITLE
Resource-Einbindung "DEV Modus"

### ISSUE THREAD

**Issue by NGWNGW** [RexDude/seo42#166]
Hi! 

Ein DEV-Modus für die Resourcen-Einbindung ist meiner Meinung nach hilfreich.

Da die Funktionen getCombinedCSSFile/getCombinedJSFile generieren die Dateien nur bei Änderungen im Quellen-Array neu. Änderungen in den Quelldateien sind nicht wirksam.

Als Workaround habe ich im Quell-Array bisher immer "?dev=time()" mit angehängt. Besser ist sicherlich ein DEV-Modus (Checkbox unter Einstellungen->Resourcen) um eine Neugenerierung bei jedem Aufruf zu erzwingen...

Gruß

**Comment by RexDude** [comment]
Hi,

hmm wenn die Quelldateien geändert werden müsste normalerweise automatisch neu kombiniert werden. Wenn das nicht der Fall ist handelt es sich vielleicht um einen Bug denn ich hab das damals eigentlich so eingebaut :)

**Comment by RexDude** [comment]
Bei mir gehts. Habs an der Demo probiert. CSS Verzeichnis in den Einstellungen auf "/files" gestellt. Dann

```php
<link rel="stylesheet" href="<?php echo seo42::getCombinedCSSFile("combined.css", array("main.css", "navigation.css")); ?>" type="text/css" media="screen" />
```

**Comment by NGWNGW** [comment]
Ok, es liegt an PHPStorm... Bearbeite ich die Quelldatei direkt auf dem FTP, dann wird die combined.css neu erstellt. Bearbeite ich die Quelldatei lokal mit PHPStorm und synchronisiere dann mit dem FTP, wird die combined.css nicht neu generiert.

**Comment by RexDude** [comment]
Kann es sein das per FTP das Änderungsdatum der CSS Dateien nicht mit übernommen wird oder anderes gesetzt wird. Die Logigk ist: Alle Datümer aller CSS Dateien zusammen ergeben eine ID. Ändert man jetzt ne Datei ändert sich das Datum und es wird neu kombiniert werden. Also schau mal in die Richtgung Datum der CSS Dateien.

**Comment by Sysix-Coding** [comment]
Das Problem hab ich auch öfters mit PhpStorm. Da wird einfach der Timestamp der Datei nicht mitaktualisert. Meistens gibt er eine kleine Info :)
Der Beitrag hat für mich das Problem gelöst:
