### ISSUE TITLE
Redirects von anderen SEO42 Rewrites

### ISSUE THREAD

**Issue by JeGr** [RexDude/seo42#168]
Ahoi,

da ich von Apache auf NGinx portieren muss, habe ich einige Probleme denen ich entgegen trete, .htaccess Gebrauch von vielen Applikationen ist eines davon, andere SEO URLs ebenfalls.

Da NGINX URLs mit .html Endung nur ungern an einen PHP Parser weiterreicht, vor allem wenn die dann auch noch 2x umgeschrieben werden (kann man irgendwie verstehen ;)), stehe ich nun vor dem Problem, ein Redaxo umzuziehen, welches vorher SEO42 URLs des Typs:

[domain]/[category]/[subcategory]/[article].html

hatte. Jetzt muss ich die Variante

[domain]/[category]/[subcategory]/[article]/

nutzen, damit das von NGINX ordentlich bearbeitet wird. Die Auto-Redirects funktionieren ja aber nur mit der alten Redaxo Rewrite Geschichte.

Gibts irgendeine Möglichkeit, die alten SEO42 URLs auch noch umzuleiten ohne dass ich da jetzt hunderte URLs manuell eintragen muss?

Grüße

**Comment by RexDude** [comment]
Das Zuabertwort Smart Redirects. Ist bereits eingeschaltet und leitet automatisch um wenn falsche Url Endung eingegeben wird.

**Comment by JeGr** [comment]
Die Funktion ist an - funktioniert aber nicht wie beschrieben. Zumindest bei mir ;)

**Comment by RexDude** [comment]
Welche Url Endung hast du eingestellt?

**Comment by JeGr** [comment]
Urls umschreiben: [x]
URL Endung: "/"
Startseite: http://domain.de/

**Comment by RexDude** [comment]
Hmm, komisch geht tatsächlich nicht. Ist dann wohl ein Bug :) Ich schau kurz mal...

**Comment by JeGr** [comment]
Freue mich wenn ich so wenigstens helfen kann ;)

**Comment by RexDude** [comment]
Kannst testen :)

**Comment by JeGr** [comment]
Ich habs mal manuell gepatcht nach deinem Diff, da ich die 4.2dev ja noch nicht übern Auto-Installer runterladen kann ;)
Scheint aber bislang bestens zu funktionieren! Kurze Randfrage: gibt der Smart Redirect bei der Umleitung ein temp. (302) oder permanent Redirection (301) Error Code zurück? Damit die Robots das auch verstehen?

**Comment by RexDude** [comment]
normal 301.

**Comment by JeGr** [comment]
Super! Dann ganz GROSSES DANKE dafür, das hat meinen Abend nochmal richtig rausgerissen :) :+1:

**Comment by RexDude** [comment]
Mein Abend wurde durch den fix auch besser :sweat_smile:

**Comment by JeGr** [comment]
Da du es vorher nicht wusstest, erschließt sich mir das zwar nicht ganz, aber wenn dem so ist - freut's mich umso mehr :grinning:

**Comment by echi1** [comment]
Hallo,
gibt es denn schon einen Thread oder Issue oder sonstwas mit den nginx Regeln?
Der andere Thread über das Thema hört vor einem Jahr mit "so machen wirs auf"....
Ich habe auch Redaxo mit SEO242 auf nginx, aber das Rewrite läuft bei mir noch nicht ganz rund. Soll ich mal einen neue Issue aufmachen, wo jeder der mit nginx bastelt was dazuschreiben kann (eigentlich wäre das dann besser auf einer Wiki Seite aufgehoben)? Oder gibts da schon was, das ich irgendwie übersehen habe?
