### ISSUE TITLE
nginx rules

### ISSUE THREAD

**Issue by mhekeler** [RexDude/seo42#169]
Hallo,
die meisten werden Seo42 auf einem Apache Server einsetzen.
Aber es gibt auch immer meh nginx Installationen. Die nötigen Rewrite Regelen für den nginx könnte man doch auch mal zusammenstellen und im Addon anzeigen?
Der andere Thread über das Thema hört vor einem Jahr mit "so machen wirs auf".... Darum poste ich mal meine Konfig, die ja sicher noch Optimierungsbedarf hat und auch unvollständig ist (z.b. Ressourcen...):

Ich habe folgende Konfiguration: Redaxo 4.6.1 mit Seo42 auf dem nginx und habe so sieht die nginx Konfig aus:
    
    ### Redaxo Settings ###
    location ^~ /redaxo/include {
      deny all;
    return 404;
    }
    location / {
      index   index.php;
      try_files $uri $uri/ /index.php?$args;
    }
    # REDIRECT ROBOTS.TXT TO SEO42 ROBOTS FUNCTION
      location /robots.txt {
      rewrite ^ /index.php?seo42_func=robots last;
    }
    # REDIRECT SITEMAP.XML TO SEO42 SITEMAP FUNCTION
      location /sitemap.xml {
      rewrite ^ /index.php?seo42_func=sitemap last;
    }

**Comment by RexDude** [comment]
Wo ist deine Beschreibung hin? ;)

Kannst du nicht so einen Converter nehmen: http://winginx.com/en/htaccess

Wenn es hier jemand was hat, kann ich es gerne in die Readem packen.

**Comment by echi1** [comment]
Ah okay...
ich habe früher mal so einen Konverter benutzt und weil da meistens nichts funktionierendes rauskam, gerieten die Konverter bei mir in Vergessenheit :-o
Ich habe mal die Seo Regeln durch http://winginx.com/en/htaccess gelassen und ein wenig angepasst:

    location / {
           index index.php;
           #try_files $uri $uri/ /index.php?$args;
           if (!-e $request_filename) {
              rewrite ^/sitemap\.xml$ /index.php?seo42_func=sitemap last;
              rewrite ^/robots\.txt$ /index.php?seo42_func=robots last;
              rewrite "^/google([a-zA-Z0-9]){1,20}\.html$" /index.php?seo42_func=googlesiteverification last;
              rewrite ^(.*)$ /index.php?$args last;
           }
           rewrite "^/(.*)\.\d{10}\.(css|js)$" /$1.$2 last;
        }
        location /download {
           rewrite ^/download[s]?/([^/]*) /index.php?seo42_func=download&file=$1 last;
        }
        location /imagetypes {
           rewrite ^/imagetypes/([^/]*)/([^/]*) /index.php?rex_img_type=$1&rex_img_file=$2;
        }

Vielleicht hat aber doch noch jemand interessante Anmerkungen dazu?

**Comment by RexDude** [comment]
Ich glaub hier passiert so schnell nix mehr, deshalb close.
Posten kann man ja trotzdem noch ;)

**Comment by mhekeler** [comment]
Schade :-(
bin wohl der einzigste, der versucht seo42 an nginx anzupassen...

**Comment by RexDude** [comment]
Schaut so aus ;) Steig halt auf Apache um ;)

**Comment by mhekeler** [comment]
Sicher nicht die schlechteste Lösung....
Aber das URL Rewrite läuft ja. Probleme hab ich nur beim include, also seo42::getCSSFile() bzw. mit min42
und ich weiß nicht, ob sich für das ein Umbau meiner Server von nginx auf Apache lohnt...

**Comment by JeGr** [comment]
@mhekeler Nein du bist nicht der einzige und @RexDude umsteigen auf Apache ist keine Lösung wenn man gerade vom Apache weg auf NGinx umsteigt ;)

Ich muss aber gestehen, dass ich kaum Regeln für den Nginx brauche, um SEO42 in Grundzügen zum Laufen zu bekommen.
Für Redaxo und SEO42 mit Einstellung "Pfade" (also kein .html am Ende) genügte:

  location ^~ /redaxo/include {
      deny all;
  }

  location / {
      rewrite "^/(.*)\.\d{10}\.(css|js)$" /$1.$2 break;
      try_files $uri $uri/ /index.php?$args;
  }

  location ~* \.(ico|css|js|gif|jpe?g|png)$ {
      rewrite "^/(.*)\.\d{10}\.(css|js)$" /$1.$2 break;
      try_files $uri $uri/ /index.php?$args;
      expires 30d;
      add_header Pragma public;
      add_header Cache-Control "public";
  }

**Comment by mhekeler** [comment]
Und mit deinen  Regeln kannst du CSS includen (seo42::getCSSFile() bzw. mit min42)?
Oder wie wird bei dir z.b. die sitemap.xml erzeugt? Oder die robots.txt?
Ich habe mir da so komische Ausdrücke wie

    rewrite ^/sitemap\.xml$ /index.php?seo42_func=sitemap last;

zusammengebastelt.

Bei dir sieht es aber viel einfacher aus :-o

**Comment by JeGr** [comment]
Sitemap und robots waren bislang keine Anfrage, das klappt mit deinen Rewrites aber problemlos, das stimmt. Der Rewrite mit den 10 Digits und css/js genügt bei mir, um css über die SEO42 Klasse versioniert ausliefern zu lassen. Source ist bei mir bspw.

/js/combined_menu.1430689491.js

was durch den Ausdruck abgefangen und auf combined_menu.js umgeschrieben wird.
