### ISSUE TITLE
addCallback in nav42

### ISSUE THREAD

**Issue by dtpop** [RexDude/seo42#170]
Dear Rudi,
I believe, that the function addCallback in nav42 has to be public.
Hugs, Wolfgang

**Comment by dtpop** [comment]
Thanks in advance, I use this function quite often to make different navigations (for example footer nav and main nav). nav42 + seo42 + less compiler = great things i would not miss!
Happy easter eggs!

**Comment by polarpixel** [comment]
Hi Wolfgang,

I would love to see an example how you use it.
Thanks in advance!

Cheers, Peter.

**Comment by dtpop** [comment]
Hallo Peter,

vielen Dank für die Nachfrage. Da ich dies wirklich immer wieder mal 
einsetze, habe ich das Beispiel hier

http://www.redaxo.org/de/forum/addons-f30/verschiedene-navigationen-in-nav42-t20351.html

hingeschrieben. Damit vermeidet man, dass man künstliche Unterkategorien 
für Navigationen machen muss.

Schöne Ostern und lieber Gruß,
Wolfgang


Am 03.04.15 um 16:19 schrieb Peter Bickel:
>
> Hi Wolfgang,
>
> I would love to see an example how you use it.
> Thanks in advance!
>
> Cheers, Peter.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RexDude/seo42/issues/170#issuecomment-89302089>.
>

-- 
Wolfgang Bund
Web Entwickler
Am Tressower See 1
23966 Groß Krankow / Tressow
Telefon 03841/6408571

http://agile-websites.de
http://ferien-am-tressower-see.de

--
Der Vernetzungskalender für Nordwestmecklenburg
http://12motive.de

**Comment by polarpixel** [comment]
Herzlichen Dank!

Ich wünsche ebenfalls ein tolles Wochenende mit vielen Ostereiern!
