### ISSUE TITLE
Sitemap Class, Methoden auf Public

### ISSUE THREAD

**Issue by Sysix-Coding** [RexDude/seo42#173]
Weil: :evergreen_tree:

Und andere Addon's sich nicht die Mühe machen müssen es 1zu1 anzupassen. Das macht ja nämlich die Methoden schon.

**Comment by RexDude** [comment]
Warum sollen die public? Meinst es gibt ein Fall wo die überschrieben werden sollen?

**Comment by Sysix-Coding** [comment]
Zurzeit hab ich bei mein asd_news AddOn die Klasse reflektiert und die Methoden auf Public gesetzt:
https://github.com/Sysix-Coding/asd_news/blob/master/classes/rex_asd_news_utils.php#L9-L20

Persönlich finde ich es unsauber und ich könnte mir gut vorstellen, dass weitere AddOns das auch gebrauchen werden. Mit Überschreibung hat es nicht zu tun :)

**Comment by RexDude** [comment]
Von ausserhalb werden die Methoden normal nicht aufgerufen.
Überschreiben macht auch nicht wirklich Sinn.
Deshalb: es bleibt wie es ist ;)
