### ISSUE TITLE
Interne Ersetzung funktioniert nicht bei Ziel-URLs mit entferneter Root-Kategorie

### ISSUE THREAD

**Issue by bega011** [RexDude/seo42#177]
Interne Ersetzung behält den kompletten Pfad/URL wenn bei der Zielseite die Root-Kategorie entfernt wird, so dass die Zielseite nicht aufrufbar ist. Selbst bei erneutem Verknüpfen lässt sich das nicht beheben. 
Bei manuell eingetragener URL (Interne URL) bei der Zielseite, funktioniert alles bestens.

**Comment by RexDude** [comment]
Ich fürchte da kann man momentan nicht viel machen. Dazu müsste ich die Rewriter Klasse komplett umschreiben :P

**Comment by bega011** [comment]
Ohje, Schade. 

Wir entfernen immer die Root-Kategorien und verlinken auf Unterseiten.
Ich löse das mit urlRewrite zur Zeit, aber dann habe ich 2 Addons gemischt, ist bissi blöd.

Naja, muss ich halt noch ein bisschen warten :(



Freundliche Grüße

Nenad Begic
Kreation




Telefon 08361-9207-406
Telefax 08361-9207-60
n.begic@tanner-werbung.com
www.tanner-werbung.com

.................................................................................................................
Tanner Werbung GmbH · Hertinger Weg 3 · 87484 Nesselwang
USt-IdNr: DE188 789 629 · Geschäftsführer: Andreas Tanner · Sitz: Nesselwang · HRB 2011
VR Bank Kaufbeuren Ostallgäu · Konto-Nr.: 5 832 225 · Bankleitzahl 734 600 46
.................................................................................................................

Am 03.06.2015 um 15:25 schrieb RexDude <notifications@github.com>:

**Comment by RexDude** [comment]
Nu hab ich doch ein workaround gefunden....wer weiss wann man zum umschreiben der rewriter klasse kommt ;)
bitte mal testen und feedback geben.

**Comment by RexDude** [comment]
@bega011 vorbildliche benennung dieses issue titel übrigens ;)

**Comment by bega011** [comment]
Mensch, ich sagte schon, du bist Klasse :+1:
