### ISSUE TITLE
Breadcrumb ignoreOfflines

### ISSUE THREAD

**Issue by ReggaePanda** [RexDude/seo42#180]
Für die nächste Version wäre super, wenn man auch über
```php
    $nav->setIgnoreOfflines(true);
```
Artikel die offline sind aus der Breadcrumb ausschließen könnte

class.nav42.inc.php Line 552
```php
    if ($this->ignoreOfflines && $article->isOffline()) {
        continue;
    }
```

**Comment by RexDude** [comment]
Yoa kann man machen.
Bekommst du ein Pull Request hin? ;)
Und Zeile 552? Bei mir gehts nur bis 538 ;)
https://github.com/RexDude/seo42/blob/master/classes/class.nav42.inc.php#L538

**Comment by ReggaePanda** [comment]
Hab gerade gesehen, dass es schon gezwungenermaßen hier in der git version ignoriert wird. Daher hat sich das erstmal erledigt... hatte vorher noch die version über den redaxo installer gezogen

**Comment by RexDude** [comment]
Oh ja...ich erinner mich wieder. Steht sogar in der Changelog :P
