### ISSUE TITLE
Redirect ist case sensitive

### ISSUE THREAD

**Issue by alexplusde** [RexDude/seo42#182]
Hi!

Wir haben gerade den Fall einer Veranstaltung, die über eine bestimmte URL auf Facebook weiterleiten soll. Um Tippfehler zu vermeiden, müssen wir die URL 6x angeben:

![Screenshot](https://dl.dropboxusercontent.com/u/110521179/Bildschirmfoto%202015-07-23%20um%2017.02.35.png)

Schöner wäre es, das allenfalls 2x machen zu müssen (mit und ohne Slash am Ende). Und ich denke nicht, dass es in der Praxis den Fall gibt, dass explizit zwischen Groß- und Kleinbuchstaben bei der Eingabe der URL unterschieden wird.

Hintergrund: Die URL wird auf einem Werbeplakat Plakat mit Großbuchstaben geschrieben, weil die Schriftart nur selbige enthält.

**Comment by RexDude** [comment]
Hey,

das ist eigentlich eher ein generelles Thema. Urls sind generell case sensitive bei SEO42. spiegel.de, gmx.de, wordpress.com sind die urls auch überall case sensitive. ich würde es daher so belassen auch für die redirects.

**Comment by RexDude** [comment]
Keine Antwort, deshalb close.

**Comment by alexplusde** [comment]
Wenn du es so belässt, ist's auch ok.

**Comment by RexDude** [comment]
Oki :)
