### ISSUE TITLE
SCSS Maps

### ISSUE THREAD

**Issue by olien** [RexDude/seo42#187]
Hi,

kann der SCS Compiler mit  SCSS Maps umgehen?

    $map: (
      key: value,
      other-key: other-value
    );

Ich bekomme immer einen 

    SCSS Compile Error: 
    parse error: failed at `$map: (` line:

--
Bei https://github.com/leafo/scssphp habe ich diesbezüglich nichts gefunden. 

Wäre sehr aufwändig die class.scssc.inc.php einmal zu aktualisieren falls die nicht aktuell ist?

LG
Oliver

**Comment by RexDude** [comment]
Hey :)

das weiss ich nicht aber anscheiend nicht. Aufwändig wars früher nicht, da der Compiler nur in einer Datei herkam, aber jetzt glaub ich hat sich das geändert...

**Comment by olien** [comment]
:-(

**Comment by RexDude** [comment]
Was der moderne Webdeveloper heut nicht alles so braucht ;)

**Comment by olien** [comment]
Ich und modern... hahaha

**Comment by olien** [comment]
Wenn ich den ganzen Kram von  https://github.com/leafo/scssphp nutze funktioniert es...
Habe es nur so in SEO42 "reingeworfen". So wird dir das nicht gefallen :-))

**Comment by RexDude** [comment]
Gut ich schau mal das ichs update für die nächste Version...

**Comment by olien** [comment]
Cool! Danke!

**Comment by RexDude** [comment]
Ist drin. Kannst ja mal testen :)

**Comment by olien** [comment]
Funktioniert. Klasse. DANKE!
