### ISSUE TITLE
Redirects mit UTM Tracking Parametern

### ISSUE THREAD

**Issue by omphteliba** [RexDude/seo42#188]
Hi,
wär es nicht sinnvoll den Redirect im SEO42 um Parameter fürs Tracking zu erweitern? Mir fallen mehrere [Gründe](http://www.beacontechnologies.com/blog/2015/08/301-redirects-and-utm-parameters/) ein das tun zu wollen (zB Vanity URLs). Ein zusätzliches Feld auf der "Redirects"/"Edit" Seite (&page=seo42&subpage=redirects&func=add) würde reichen um die [UTM Syntax](https://support.google.com/analytics/answer/1033867?hl=en) hinzuzufügen. Und dann den Wert beim Erzeugen der URL anhängen.

thx!

O.

**Comment by RexDude** [comment]
Hi und danke für die Idee und sorry für die späte Rückmeldung :)
Finde die Idee interessant aber stelle ich erstmal hinten an.
Deine PR habe ich mir angeschaut. Das mit dem extra Textfeld kann man machen, aber ein Nutzer wird kaum Ahnung haben was er da eintragen soll und ausserdem muss man hier wenn man mehere Redirects hat per Copy und Paste die Felder befüllen.
Interessanter wäre halt eine vollautomatische Lösung, sprich man schaltet die Einstellung ein und muss sonst nix mehr groß machen :) Ob das aber geht habe ich noch nicht durchgedacht...

**Comment by omphteliba** [comment]
Hi,
vollautomatisch wird da nix gehen, da Du über die Werte unterschiedliche Infos übergeben kannst. 

Für den Spezialfall "Google UTM"-Werte für Google Analytics gibt es einen Builder: https://support.google.com/analytics/answer/1033867?hl=en

Aber vllt will ja jemand anderes statt GA, Bing Analytics, oder was weiss ich da übergeben :) Darum hatte ich es erstmal als dummes Feld angelegt.

Oder wie hattest Du das gemeint?

**Comment by RexDude** [comment]
Wusst gar nicht dass es Bing Analytics gibt ;)
Dachte auch es wären nur 2 Parameter die relevant sind.
Ich weiss jetzt auch nicht. Könnten das Feld schon reinnehmen mit einer Einstellung zum ein und ausschalten. Aber ich glaube es ist net wirklich nötig. Wer ernsthaft an Statistiken interessiert ist sollte lieber die Server Logs auswerten. Es gibt heut genung Leute die die ganzen Tracker per Browser Addon blockieren...sprich auf GA sollte man sich nicht wirklich verlassen und da hab ich vermutlich auch nicht so das Bedürfnis das Feld einzubauen. Oder wie siehst du das? ;)

**Comment by omphteliba** [comment]
"Bing Analytics" war nur ein Platzhalter für die anderen Analyse- und SocialMedia-Tools die es gibt, die via URL-Parameter Meta-Informtionen übergeben (Piwik, KISSmetrics, Hootsuite ...). 

Klar ist GA weit davon perfekt zu sein; vor allem die kostenlose Version, die rundet ja sehr schnell. Aber trotzdem ist das ein gerne benutztes Tool. Aber das müssen wir jetzt nicht hier diskutieren ;)

**Comment by RexDude** [comment]
Ich frag mich halt obs Leute gibt die das wirklich nutzen werden ;)

**Comment by omphteliba** [comment]
Ok, da ich dich nicht überzeugen kann, kann ich das Feature vllt als Plugin umsetzen?

**Comment by RexDude** [comment]
Also wenn du es aufjedenfall nutzen wirst bau ichs ein mit noch ner Einstellung dazu damit da nicht irgend ein Mist eingegeben wird aus Unwissenheit.

**Comment by omphteliba** [comment]
Also ich muss das Feature auf jeden Fall einbauen: meine SM-Mädels brauchen das :)
Ich schreib auch gerne einen Hilfetext dazu.

**Comment by RexDude** [comment]
SM? ;) Ok...damit die Mädels glücklich sind ;)
Kommt in die 4.3.0 mit rein.

**Comment by omphteliba** [comment]
;) SM = SocialMedia

Danke!

**Comment by RexDude** [comment]
Jetzt hab ich mal ne dumme Frage: wozu brauchen wir dass extra Feld überhaupt wenn man doch eh an die TargetUrl quasi mit einem vorangehenden ? die tracking params anhängen kann?
Weil das war glaub der Grund warum ich nie so Feuer und Flamme wurde für die Idee. Bin aber erst jetzt drauf gekommen ;)

Also jetzt bin ich doch dafür das draussen zu lassen und vielleicht irgendwann mal für GA ein automatisches anhängen zu machen. Ausser du schüttelst noch ein wichtiges Argument aus dem Ärmel ;)

**Comment by omphteliba** [comment]
Ahso, ja dann. Sag das doch gleich, da hätten wir uns ja die ganze Diskutiererei sparen können ;)
Na dann geht das ja schon! Wunderbar, ich habs nur nicht gerafft! Ja dann braucht man das ja garnicht!

**Comment by RexDude** [comment]
Cool :)
Ja hätten wir, habs aber auch ne gerafft...erst als ich angefangen hab es einzubauen :)
Schöne Grüße an die SM Mädels ;))
