### ISSUE TITLE
Rewrite bei Sprache 中文 funktioniert nicht

### ISSUE THREAD

**Issue by chrfickinger** [RexDude/seo42#190]
Obwohl die URL richtig geparst wird, zeigt SEO42 nur die 404-Seite.

**Comment by chrfickinger** [comment]
Offensichtlich funktioniert auch das Parsen der Url nicht fehlerfrei. Unterstützt SEO42 überhaupt "exotische" Sprachen?

**Comment by RexDude** [comment]
Benutzt du denn "Url Encode"?
Wenn du mämlich den "Sepcial Chars" Rewrite Mode verwendest, muss es natürlich für jedes chinesische Zeichen eine Umschreibungsvariante geben ;)

**Comment by chrfickinger** [comment]
Ah super, vielen lieben Dank für dir schnelle Antwort. Das hilft schon mal für die Urls. Allerdings stehe ich nun noch vor dem Problem dass meine Seite in 2 chinesischen Sprachen umgesetzt werden soll.

zh-cn (Simplified Chinese) und zh-tw (Traditional Chinese)
Bei Code habe die Werte entsprechend eingetragen, es werden aber nur die ersten beiden Zeichen benutzt, also "zh" für beide. Hast du dafür einen Tipp?

**Comment by RexDude** [comment]
Leider kann man ohne hier ohne Erweiterung der ganzen LangPresets geschichte nicht wirklich was machen. Das aufbohren des Ganzen ist aber geplannt auch wegen dem hier: https://github.com/RexDude/seo42/issues/183
Individueller Langslug müsste auch noch dazu. 
Wenn sich hier ein Sponsor findet der das ganze finanziell unterstützt könnt ich es sicherlich schneller einbauen ;)

Bis dahin würd ich cn und tw als LangCode definieren. Ist zwar net optimal aber so würde es erstmal gehen.

**Comment by chrfickinger** [comment]
Na das hört sich doch super an, über das Sponsoring können wir reden. Kann ich dich irgendwie kontaktieren?

**Comment by RexDude** [comment]
Da du ja auch im REDAXO Forum bist: schick mir dort einfach ne PM mit deinen Kontaktdaten und ich melde mich bei dir (am liebsten ab nächster Woche).

**Comment by RexDude** [comment]
Lang Url Slug kann nun gesondert eingestellt werden.
