### ISSUE TITLE
Sprachen Presets

### ISSUE THREAD

**Issue by alexplusde** [RexDude/seo42#194]
Ist mir am Redaxo-Tag aufgefallen:

Wenn man schon für jede Sprache den Preset-Wähler hat, könnte man den auch beim Tab für Sprachen gleich haben? (Global Special Chars etc.)

**Comment by RexDude** [comment]
Nö, weil die Presets ja weit mehr Felder befüllen und so. Einfach copy und paste verwenden ;)
