### ISSUE TITLE
nav42: Breadcrumb-Bug entdeckt?

### ISSUE THREAD

**Issue by dpf-dd** [RexDude/seo42#196]
Hallo Rudi,

noch frisch vom Redaxo-Tag motiviert gleich mal ein kleines Ärgernis an deiner tollen Breadcrumb-Klasse von SEO42/NAV42... Wäre schön, wenn du dir das mal anguckst...

Folgendes Problem:
Alle Unterseiten, die in Unterkategorien der Startseite (also $REX['CATEGORY_ID'] == 1) liegen, werden im Breadcrumb-Menü leider doppelt ausgegeben!

Bsp.:
Struktur-Verwaltung: "Index" (Cat-ID 1) => "Suchergebnisse" (Untercat von 1) => "Suchergebnisse" (Startartikel)
...führt zur Breadcrumb-Ausgabe: "Index => Index => Suchergebnisse"

Die Ausgabe ist natürlich absolut logisch und auch korrekt. Aber besser wäre an dieser Stelle natürlich, dass da nur 1x Index steht... Man müsste quasi in die nav42-Klasse so erweitern, dass für Unterkategorien der Startartikel-Kategorie der einleitende "Index" nicht geparst wird, die Breadcrumb-Nav sozusagen erst auf 2. Ebene beginnt.

Vielen Dank und MfG
Stefan / dpf_dd

**Comment by RexDude** [comment]
Kannst du bitte mal selber schaun?
Evtl. hilft dir der Autor der Methode @webghostx :)

**Comment by RexDude** [comment]
Hier an der Stelle gehts net weiter. Bitte das Navigation Factory Addon abchecken und dort evtl. nochmal reporten wenn Prob noch vorhanden.
