### ISSUE TITLE
Feature Request: href title

### ISSUE THREAD

**Issue by chrfickinger** [RexDude/seo42#198]
Man könnte den SEO Tab um ein Feld für einen href title ergänzen.
Aktuell muss ein href title="" über ein Meta-Feld gepflegt werden. Besser aufgehoben wärs es aber bei SEO. Was meinst du ?

Benutzbar z.b.:
a href="#" title="seo42::getHrefTitle(0)"

**Comment by RexDude** [comment]
Hmm ich weiss nicht so genau. SEO Tab bezieht sich auf den Artikel ansicht. href kommt ja in nem Link vor.

**Comment by chrfickinger** [comment]
Es ist allerdings schon ein SEO Thema den Titel eines Links anzupassen. Ich dachte, weil man auf dem SEO Tab ja auch den Titel einer Seite angibt, so könnte man einen abweichenden Href Titel angeben (falls die Seite mal verlinkt wird) und als Fallback den SEO Seitentitel dafür nehmen.

**Comment by RexDude** [comment]
Es gibt die Meinung da draussen, dass href title wenig bis gar keinen Einfluss aufs SEO hat, siehe: http://www.searchenginejournal.com/how-to-use-link-title-attribute-correctly/
Er hier ist der Meinung das es ne reine Usabolity Geschichte ist: http://emanuel-kluge.de/html-css/das-title-attribut-ist-kein-seo-spielzeug/
Allerdings welcher User nimmt sich schon die Zeit auf einem Link stehen zu bleiben nur um den Tooltip lesen zu können. Da klickt man doch einfach drauf und schaut wo hins führt stattdessen eher (meine Meinung).

Desweiteren gibt die seo42 Klasse die Daten zum aktuellen Artikel aus. Du hast aber oft in einem Artikel Links zu verschieden anderen Artikel wo ja der title auch erscheinen soll. Das heisst mit der aktuellen Philosophie der seo42 Klasse kommt man auch nicht weiter.

Lange Rede kurzer Sinn: aus SEO Sicht sehe ich keine Notwendigkeit eines weitere title Feldes für Links. Aus Usability Sicht schon, allerdinds würde das dann eher in das neue Navigation Factory Addon passen wo es vermutlich (weiss net ob für die erste Version) einen Navigationstab geben wird + dann die entsprechenden Nav Klassen die dann den Titel mit ausgeben können.

Also hier kommts net rein aus oben genannten Gründen ;)

**Comment by chrfickinger** [comment]
Ok, danke fürs Feedback. War ja nur ein Vorschlag :)

**Comment by RexDude** [comment]
Kein Problem. Jeder Zeit wieder ;)

**Comment by RexDude** [comment]
Der Vollständigekisthalber: Würde man ein Feld haben href Title so hat man aber trotzdem nicht sichergestellt, dass der Benutzer wenn er im CK/Tiny/Markitup Editor einen internen Link setzt das href Feld automatisch befüllt wird. Dazu müsste man die Editoren aufbohren was aber aufwändig ist. Weil ohne dass macht es nicht wirklich Sinn weil ja der User dann trotzdem von Hand das title Attribute setzen müsste.

**Comment by chrfickinger** [comment]
Ja, das stimmt. Ich dachte aber auch eher an die Verwendung ausserhalb des Editors. Mit der Lösung des href-Title als Meta-Feld kann ich aber leben.
