### ISSUE TITLE
@import in der SCSS-Datei funktioniert nicht

### ISSUE THREAD

**Issue by bega011** [RexDude/seo42#202]
Es scheint als @import von anderen SCSS-Dateien, die in der Master-SCSS-Datei importiert werden, nicht funktionieren würde: 
z.B. wenn in die styles.scss weitere importiert werden: @import "variables"; @import "mixins" usw.

Mit less-Dateien funktionieren Importe ganz gut.

**Comment by RexDude** [comment]
Masgt du (oder jemand anderes) mal selber schauen. Ich vermute es muss ein Import Pfad der scss Klasse bekanntgegeben werden. Hier in der Gegend: https://github.com/RexDude/seo42/blob/master/classes/class.rex_resource_includer.inc.php#L284

**Comment by bega011** [comment]
Du meinst wie bei less:
$scss->setImportDir($path['dirname']);

**Comment by RexDude** [comment]
ja.

**Comment by bega011** [comment]
Es hat nicht funktioniert, dann wird im HTML-Header nach src=" einfach leer, danach kommt gar nichts, die Seite ist leer.

**Comment by RexDude** [comment]
Leere Seite = PHP Fehlermeldungen werden unterdückt
Du kanckst die Nuss....ich bin überzeugt :)

**Comment by RNGesus** [comment]
Ohne es wirklich getestet zu haben, setze ich mein Pferd auf:
`$scss->addImportPath($path['dirname']);`

**Comment by bega011** [comment]
Hast du gut gesetzt ;)
Funzt :)

**Comment by alexplusde** [comment]
Ach, das war ein Bug? Danke fürs fixen!

**Comment by RexDude** [comment]
It was not a Feature, it was a Bug ;)

**Comment by alexplusde** [comment]
Was jetzt noch etwas ärgerlich ist in dem Zusammenhang, ist, dass man das parsen einer scss-Datei nicht durch eine geänderte und inkludierte scss-Datei anstoßen kann.

Gibt's da eine Möglichkeit, dass die kompletten scss-Dateien geparst werden, ohne dass man die im Template verlinkte scss-Datei auch neu abspeichert / neu hochlädt, um den Zeitstempel der scss-Datei   zurückzusetzen?

Wie macht ihr das beim Entwickeln?

**Comment by RexDude** [comment]
Sowas könnte man nur checken wenn man anfangen würde die SCSS nach @import Statments zu parsen und dann die filestamps vergleicht von diesen dateien etc. das ganze würde dann etwas ausufern denke ich.

**Comment by alexplusde** [comment]
was nicht ideal wäre, wäre, wenn das Löschen der geparsten css-Datei erkannt wird und automatisch zu einer Neuberechnung führt. Weil css-Datei löschen geht schneller als "datei herunterladen, bearbeiten, speichern, neu hochladen"
