### ISSUE TITLE
Rewrite von Parameter in Url

### ISSUE THREAD

**Issue by chrfickinger** [RexDude/seo42#203]
Hi Rudi,
gibt es eine einfache Möglichkeit mit SEO42 an einen URL-Paramter zu kommen um die Url dann umzuschreiben?

z.B. /pfad/pfad/?topic=test
=> /test-site

**Comment by RexDude** [comment]
Das url_control Plugin ist für sowas gedacht.

**Comment by chrfickinger** [comment]
Danke für die schnelle Antwort. Schau ich mir an.

**Comment by RexDude** [comment]
Schreib solche Fragen besser ins Forum wenns geht :)
