### ISSUE TITLE
Compiler lessphp mit less.php ersetzen

### ISSUE THREAD

**Issue by RexDude** [RexDude/seo42#204]
da die entwicklung von lessphp seit 1 jahr still steht überlege ich ob es nicht sinnvoller wäre auf less.php umzusteigen. @DanielWeitenauer was meinst du? kämst du klar wenn dein plugin damit dann nicht mehr gebraucht werden würde? :)

**Comment by DanielWeitenauer** [comment]
Das sehe ich nicht als Problem :) Außer, das sich das Plugin in den passenden EP einhängt passiert dort eigentlich nichts interessantes und less.php direkt in seo42 zur Verfügung zu haben, ist auf jeden Fall bequemer ;)

**Comment by RexDude** [comment]
Optimal. Dann tausch man den jetzt endlich mal aus :)

**Comment by RexDude** [comment]
@DanielWeitenauer Könntest du mal schauen und testen ob das so passt? Habe boostrap.less damit schon mal erfolgreich Kompilieren können :)

**Comment by DanielWeitenauer** [comment]
Hab erst mal nur auf Deinen Commit geschaut. ;) Ich komme wohl erst heute Abend dazu, das mal in Ruhe zu testen. 
Was mir spontan einfiel: Du könntest noch überlegen, den Output mit der Option 'compress' => true direkt zu komprimieren. Wäre dann noch eine Überlegung, ob man die Option fürs Debugging abschalten kann...

**Comment by RexDude** [comment]
Ok. Ich habe schon gesehen das du das bei dir drin hattest. Da ja jede Resource per Gzip komprimiert wird habe ich mal ein test gemacht und ein minifiziertest CSS und ein Nicht minifiziertes CSS komprimiert. Ersparnis war 1KB (19,7KB zu 20,5KB oder so). Also quasi nix. Was wir aber haben ist halt die Lesbarkeit auch später wenn man mal wieder ran muss um was zu ändern. Deshalb würd ichs so belassen :)

**Comment by RexDude** [comment]
So wie du die Import Dirs angegeben hats, hats bei mir übrigens nicht gefunzt. Musste das ganze in ein Array packen und dann übergeben.

**Comment by DanielWeitenauer** [comment]
Bei mir war es auch ein Array, der wurde angepasst, wenn er noch kein Array war. Warum ich das über eine if-Abfrage gemacht habe, kann ich mich allerdings nicht erinnern.

**Comment by RexDude** [comment]
Ok. Kommst du mit compress = false klar?

**Comment by DanielWeitenauer** [comment]
Klar. Hatte ja oben schon, wie Du auch, angemerkt, dass es für das Debugging nicht so ideal ist. Und wenn es mit dem gzippen kompensiert werden kann, um so besser. Ansonsten gibt es ja auch noch min42. :)

**Comment by RexDude** [comment]
Ok. Less.php ist drin.
