### ISSUE TITLE
Redirect Eingabe: Kein Abbrechen möglich

### ISSUE THREAD

**Issue by DanielWeitenauer** [RexDude/seo42#207]
Beim Klick auf "abbrechen" bei einer Redirect-Eingabe kann man ohne eine Eingabe nicht die Seite verlassen, es erscheint stets der Alert "Die alte URL muss mit "/" beginnen."

**Comment by RexDude** [comment]
Wird gefixt. Hab ich anscheinend noch die draufgedrückt auf Abbrechen ;)
PR welcome :)
