### ISSUE TITLE
URL-Generierung ist bei vielen Artikeln sehr, sehr langsam

### ISSUE THREAD

**Issue by tzfrs** [RexDude/seo42#208]
Hi RexDude,

ich habe eine Seite mit ca. 7000 Artikeln. Wenn man einen Artikel anlegt, loescht, metadaten aktualisiert oder den Cache loescht, dann werden die URLs ja neu generiert. Das Problem, dass ich habe, ist, dass das sehr langsam geht. Es dauert zwischen 30 und 90 Sekunden. Aber es ist echt nervig, wenn man mal eben einen Artikel anlegen will, dass man so lange warten muss.

In einem anderen Projekt habe ich die gleiche Anzahl an Artikeln, damals wurde aber noch RexSeo benutzt. Dort dauert die URL-Generierung nur 10 Sekunden, was auch nicht gerade "schnell" ist, aber noch aushaltbar.

Kennst du dieses Problem? Gibt's dafür eine Loesung?

**Comment by RexDude** [comment]
Hi,

Sync Redirects Einstellung ist aus?

**Comment by tzfrs** [comment]
Hi,

ja ist ausgeschaltet. Habe eigentlich fast überall die default settings. Das einzige was angepasst wurde, sind die Special Chars zum Rewriten für die einzelnen Sprachen, die ich habe.

**Comment by RexDude** [comment]
7000 Artikel mal X Sprachen?
Oder ingsgesamt 7000?

**Comment by tzfrs** [comment]
Hi, 

insgesamt 7000. Also die Datenbanktabelle `rex_article` hat 6721 Eintraege

**Comment by RexDude** [comment]
Ok. Ja das ist leider ein Problem wo ich aktuell nix machen kann. Wobei 30 bis 90 sek schon recht lang ist. Soviel mehr macht SEO42 eigentlich auch nicht, dass diese Extrazeit gerechtfertigt wäre. Wobei ja auch 10 Sek zu lang ist.

Ich denke es liegt halt an der Architektur der Pathlist Geschichte. Vermutlich müsste man sich da mal was neues, effektiveres Überlegen.
Kannst ja zum Spaß mal yrewrite testen. Das müsste performanter sein :)

**Comment by tzfrs** [comment]
Hi,

danke schon einmal für deine Antwort. Kann man mit yrewrite auch eigene URLs setzen? Also wo unterscheiden sich eure Funktionalitaeten? Ich kann naemlich schlecht einfach so ein anderes Addon verwenden, ohne es getestet zu haben. Das verstehst du ja sicher. Aber danke schon einmal für deine schnelle Antwort :+1:

**Comment by RexDude** [comment]
Versteh ich. Glaub schon dass das geht.
Man könnte ja mal ne Test install machen dachte ich. Vielleicht dauerts da ja auch so lang, dann kann man am Speed aktuell nix drehen...

**Comment by tzfrs** [comment]
Ich hab den YRewriter mal ausprobiert. Artikel anlegen, loeschen geht bisher instant ohne Wartezeit. Das ist schonmal super!

Allerdings fehlen da leider ein paar Features, die dein AddOn hat 

1. Kein Lang-Slug für bestimmte Sprachen
2. Special Chars Ersetzung
3. Wahrscheinlich noch mehr, die ich auf dem ersten Blick nicht sehe

Aber die kann ich auch selbst noch nachbauen.

**Comment by RexDude** [comment]
Beide Addons haben Stärken und Schwächen aktuell :)
