### ISSUE TITLE
Rex 4.6.2 läd keine Seiten mehr nach SEO42 Addon Installation

### ISSUE THREAD

**Issue by gupi** [RexDude/seo42#209]
Brandneues jungfräuliches Redaxo 4.6.2 installiert.
meine Testseite nutzt mein Testtemplate mit folgenden Inhalt:<h1>Hallo Welt</h1>
Nach SEO42 installation und aktivierung kann auf keine Seite im root Verzeichnis mehr zugegriffen werden!
Setup von SEO41 wurde durchgeführt und dabei die htaccess datei kopiert.
Deinstallieren von SEO42 wir mit Fehler quittiert:
Fatal error: Class 'seo42_utils' not found in /Users/gunterpietzsch/Documents/virtual_hosts/hhof/redaxo/include/addons/seo42/uninstall.inc.php on line 13
Call Stack
#	Time	Memory	Function	Location
1	0.0041	305256	{main}( )	../index.php:0
2	0.1757	5851608	require( '/Users/gunterpietzsch/Documents/virtual_hosts/hhof/redaxo/include/pages/addon.inc.php' )	../index.php:275
3	0.1779	5863072	rex_baseManager->uninstall( ??? )	../addon.inc.php:133
4	0.1779	5863624	rex_addonManager->includeUninstaller( ???, ??? )	../class.rex_manager.inc.php:125
5	0.1781	5868136	require( '/Users/gunterpietzsch/Documents/virtual_hosts/hhof/redaxo/include/addons/seo42/uninstall.inc.php' )	../class.rex_manager.inc.php:363

Gruß
Gunter

**Comment by RexDude** [comment]
Bei mir läufts :)
Kann dir von hier aus nicht helfen.
Insbesondere nicht mit der Fehlerbeschreibung "lädt keine Seiten mehr".
Wegen "Class 'seo42_utils' not found". Schau halt warum die Datei bei dir nicht da ist. Mitgeliefert wird sie ja ;) 
Desweiteren würd ich dich bitten sowas besser ins Forum zu posten weil evtl. da auch andere dir weiter helfen können. Das klingt für mich erstmal nicht nach einem SEO42 Bug. Eher Server/Recte Probs etc.

**Comment by gupi** [comment]
Hi,
nachdem ich hier weitergesucht habe, zeigt sich die htaccess als der Verursacher.
Da ich MAMP als virtuellen Server für meine Entwicklung einsetze, muss ich das port 8888 für den Aufruf der Seiten nutzen.
Das funktioniert so lange, wie ich im System (Backend) als URL "hhof.local:8888/" eingetragen habe.
Sobald ich dort aber den, lt. SEO42 geforderten Eintrag "http://hhof.local:8888/" vornehme, funktioniert die aktuelle rewrite rule nicht mehr. Im Browser erscheint "hhof.local/xyz.html" statt "hhof.local:8888/xyz.html“ und das quittiert firefox mit der Meldung dass die Seite nicht geladen werden kann. (Hier war meine Fehlerbeschreibung tatsächlich etwas unterbelichtet)

Ich komme mit meinem oben beschriebenen Workaround erstmal durchaus weiter und mein Verständnis für die definition von rewrite rules in der htaccess ist leider eher rudimentär - sprich dem bin ich ohne vorhergehende Grundlagenforschung nicht gewachsen wenn ich hier tiefer gehen müsste.


Noch ein schönes Wochenende
Gunter

**Comment by RexDude** [comment]
Hey, Danke! Damit kann ich jetzt sehr gut was anfangen. Ich werd versuchen das zu testen und den Fehler zu finden wenn da einer ist.

**Comment by RexDude** [comment]
Hat sich dass erledigt? Ich schliesse, sonst nochmal melden.
