### ISSUE TITLE
"Fatal error: Class 'sql' not found" auf der Page "Redirects"

### ISSUE THREAD

**Issue by mizmiz** [RexDude/seo42#211]
Aden Version: 4.4.1
PHP Version: 5.6.10

> Fatal error: Class 'sql' not found in /Users/m/htdocs/schloss-liebenberg/03_www/redaxo/include/addons/seo42/pages/redirects.inc.php(138) : runtime-created function on line 6

I denke in **/redaxo/include/addons/seo42/pages/redirects.inc.php** in **Zeile 128** muss es 
> $sql = rex_sql::factory();

heissen.

**Comment by RexDude** [comment]
Danke fürs reporten.
Schau mal ob das jetzt passt bitte.

**Comment by mizmiz** [comment]
Nein, leider nicht.

> Fatal error: Call to undefined function rex_sql() in [...]/redaxo/include/addons/seo42/pages/redirects.inc.php(138) : runtime-created function on line 6

**$sql = rex_sql::factory();** scheint mir die korrekte Lösung zu sein. Ist ja auch in Zeile 7 und Zeile 37 schon in Verwendung

**Comment by RexDude** [comment]
Dann probiers doch bitte aus und sag mir definitiv ob das die richtige Lösung ist :)
Dann kann ich es so übernehmen.

**Comment by mizmiz** [comment]
> $sql = rex_sql::factory();

behebt das Problem. Getestet auf PHP 5.5.26 und PHP 5.6.10

**Comment by RexDude** [comment]
Ok danke. Warum dass aber so sein muss verstehe ich nicht.
