### ISSUE TITLE
"Force Download" Dateiendungen

### ISSUE THREAD

**Issue by alexplusde** [RexDude/seo42#213]
Hi Rudi,

beim Hoster Domainfactory hatte ich das Problem, dass die force download-Pfade zu einem 404er führten. Standardmäßig ist in den Settings ja ".pdf" eingetragen, ich hatte die Liste um andere Endungen erweitert.

Workaround: Die Downloads funktionierten bei mir nur, wenn ich Dateiendungen ohne Punkt-Zeichen eingebe. Wenn ich bspw. "pdf", "jpg", "notebook" eingebe, wird der Download gestartet.

**Comment by RexDude** [comment]
Hey Alex,
also zuerstmal ist standardmäßig nix in den Settings ;)
Desweiteren muss man tatsächlich die reine Dateiendung eingeben also ohne Punkt. 
Das es mit Punkt auch geht wunder mich ;) Muss es evtl. rausfiltern :)

**Comment by alexplusde** [comment]
Oh, kein Default? Kann sein, dass ich mich täusche. 

Dann wandle ich mein Anliegen entsprechend so ab, dass eine möglicherweise noch kommende Umbenennung der einzelnen Funktionen inklusive Erläuterungstexten das berücksichtigt ;)

In mForm und xForm sind Dateiendungs-Punkte meines Wissens erforderlich, deswegen war das wohl auch das, was ich intuitiv in dieses Feld eingegeben hatte.

**Comment by RexDude** [comment]
> Oh, kein Default? Kann sein, dass ich mich täusche. 

Ganz sicher kein Default. Wollte das man es explizit aktivieren muss aus Sicherheitsgründen.

Kommt in die Hilfe mit rein ;)

**Comment by alexplusde** [comment]
super!

**Comment by RexDude** [comment]
yo war schon wichtig :)
