### ISSUE TITLE
Feature: HTML reduzieren

### ISSUE THREAD

**Issue by alexplusde** [RexDude/seo42#214]
https://developers.google.com/speed/docs/insights/MinifyResources

Entsprechend der Google Pagespeed Insights-Empfehlungen zu "HTML reduzieren"
lasse ich über den XOutputFilter folgende Ersetzungen vornehmen:

*Zeilenumbrüche filtern*
´´´/[\n]+/´´´
in
´´´<?php echo(""); ?>´´´
(irgendwie durfte bei mir da das Feld nie leer sein)

*Kommentare entfernen*
´´´//ms´´´
in
´´´ ´´´

Das gehört m.E. in SEO42 als opt-in verbaut.

**Comment by RexDude** [comment]
Für die Hardcore Optimierer kann mans schon einbauen ;)

**Comment by RexDude** [comment]
Aber ich glaube min42 macht sowas auch schon.

**Comment by alexplusde** [comment]
Musste erst mal nach min42 googlen und habe den Thread dazu gesehen.
http://www.redaxo.org/de/forum/addons-f30/plugin-min42-fur-seo42-t20133.html

Wenn PageSpeed ein Instrument ist, um die Performance einer Website aus Sicht von Google zu messen und das bemängelt wird, ist das Feature eigentlich eine gute Sache. 

(Okay, wir könnten uns stattdessen auch darüber unterhalten, dass Bilder aus dem Image-Manager noch viel zu groß sind - aber es git halt kein image_manager42 in deinem Repertoire :P)

**Comment by RexDude** [comment]
Hmmm....könnten SEO42 dahingehend ausstatten auch solche micro optimazations hinzubekommen soweit es geht. ich persönlich brauchs nicht, hab dann doch auch mal gerne noch sprechenden code wenn ich mal was nachschauen oder änderungen machen muss. aber ein nettes feature wäre es schon. 

> (Okay, wir könnten uns stattdessen auch darüber unterhalten, dass Bilder aus dem Image-Manager noch viel zu groß sind - aber es git halt kein image_manager42 in deinem Repertoire :P)

das kann ja noch kommen ;)

**Comment by fietstouring** [comment]
Kann ich nicht verifizieren, dass die Sache einen Einfluss auf das Ergebnis von Pagespeed hat... habe auch lieber lesbares HTML. Pagespeed hat noch bei keiner Seite deswegen gemeckert. Ausserdem ist  Pagespeed ein Tool mit ziemlich unvorhersehbaren Ergebnissen...

**Comment by RexDude** [comment]
Microptimazations lassen wir dann erstmal weg, der Aufwand lohnt sich nicht wirklich.
