### ISSUE TITLE
favicons

### ISSUE THREAD

**Issue by fietstouring** [RexDude/seo42#216]
Hab herausgefunden dass die favicons idealerweise im website root liegen und nicht in einem unterordner. ausserdem sollte die link rel="shortcut icon" dekl. entfernt werden.

[https://mathiasbynens.be/notes/rel-shortcut-icon](url)

**Comment by RexDude** [comment]
Ich mag aber keine 20 Dateien in mein Webroot packen. Aber du kannst doch den Pfad einstellen wenn du getFavIconFile() benutzt? Oder halt einfach / und dann die files.

**Comment by RexDude** [comment]
Ich schliesse dann mal. Einfach Einstellung machen.
