### ISSUE TITLE
CSS Dateien werden nicht geladen

### ISSUE THREAD

**Issue by tbaddade** [RexDude/seo42#220]
Struktur
```
/resources/css/
/resources/fonts/load_font_file.css
```

`<?= seo42::getCSSFile("../fonts/load_font_file.css"); ?>`
ergibt
`/resources/css/fonts/load_font_file.css`

**Comment by RexDude** [comment]
Hey :)

Ich vermute dass der Relative Pfad Probleme macht. (../ )
Benuzte entweder `getCSSFile()` und schmeisse alles in den css Ordner (gerne mit Unterordnern) oder aber `getResourceFile('/resources/fonts/load_font_file.css')`.
