### ISSUE TITLE
Automatische Redirects anlegen wenn Kat/Art geändert/gelöscht

### ISSUE THREAD

**Issue by RexDude** [RexDude/seo42#67]
Vorgeschlagen von @SigmaAlphaPi und @polarpixel
...muss noch gründlich durchdacht werden.

**Comment by RexDude** [comment]
Das halte ich mittlerweile für problematisch, da evtl. unnötige Redirects oder Umleitungsfehler entstehen können. Z.B. URL A wird in URL B geändert. Nun wird es zurückkorrigiert = Umleitunsgfehler. Oder aber es war ein Versehen = unnötiger Redirect. etc.

Einzigst sinnvolle Maßnahme: Checkbox Redirect anlegen wenn Kat geändert wird. Allerdings weiss ich net ob das ein Redakteuer verstehen wird bzw. dann auch macht.

**Comment by polarpixel** [comment]
Hui, da haste jetzt aber lang nachgedacht, 1,5 Jahre ... ;-)
Alles klar, nicht so wichtig.

**Comment by RexDude** [comment]
Manche Dinge brauchen halt Zeit ;)

**Comment by tbaddade** [comment]
> Z.B. URL A wird in URL B geändert. Nun wird es zurückkorrigiert = Umleitunsgfehler. Oder aber es war ein Versehen = unnötiger Redirect. etc.

Ggf. alte Url und neue Url mit den Redirect-Daten vergleichen und dann eher den Redirect-Eintrag löschen anstatt einen weiteren Eintrag aufzunehmen. Ich weiß nicht ob das Rexseo drin hatte, aber dort wurden zumindest Endzeiten gesetzt und dann war der Redirect offline.

**Comment by RexDude** [comment]
Das Feature ist jetzt doch realisiert worden und sollte in der 4.2.0 drin sein.

**Comment by polarpixel** [comment]
Hehe, Dir war wohl langweilig? ;-)
